import test from 'node:test';
import assert from 'node:assert/strict';
process.env.NODE_ENV='test';process.env.PLATFORM_ENV='development';

test('platform control API contract suite', async (t)=>{
  const {app}=await import('../apps/platform-control-api/src/server.js');
  const token='dev.'+Buffer.from(JSON.stringify({userId:'operator-1',tenantId:'platform',roles:['platform-admin'],permissions:['platform:write'],mfa:true})).toString('base64url');
  const headers={authorization:`Bearer ${token}`};


  await t.test('health is public but control APIs require operator authentication',async()=>{assert.equal((await app.inject({method:'GET',url:'/health'})).statusCode,200);assert.equal((await app.inject({method:'GET',url:'/v1/control/overview'})).statusCode,401)});
  await t.test('operator can create auditable non-destructive change',async()=>{const response=await app.inject({method:'POST',url:'/v1/control/changes',headers,payload:{environment:'development',operation:'disable-capability',capability:'cache',desired:{enabled:false,fallback:'memory'}}});assert.equal(response.statusCode,201);assert.equal(response.json().actorId,'operator-1');assert.equal(response.json().environment,'development')});
  await t.test('control API rejects a change scoped to another environment',async()=>{const response=await app.inject({method:'POST',url:'/v1/control/changes',headers,payload:{environment:'production',operation:'disable-capability',capability:'cache',desired:{enabled:false,fallback:'memory'}}});assert.equal(response.statusCode,409);assert.equal(response.json().error.code,'ENVIRONMENT_SCOPE_MISMATCH')});
  await t.test('direct infrastructure destroy is rejected',async()=>{const response=await app.inject({method:'POST',url:'/v1/control/changes',headers,payload:{environment:'development',operation:'destroy-infrastructure',capability:'cache',desired:{}}});assert.equal(response.statusCode,409);assert.equal(response.json().error.code,'DESTRUCTIVE_ACTION_REQUIRES_ORCHESTRATOR')});
  await t.test('secrets page accepts metadata but rejects plaintext secret values',async()=>{const response=await app.inject({method:'PUT',url:'/v1/control/pages/secrets',headers,payload:{secretValue:'do-not-store'}});assert.equal(response.statusCode,400);assert.equal(response.json().error.code,'PLAINTEXT_SECRET_FORBIDDEN')});
  await t.test('secrets page rejects nested password token and credential fields',async()=>{for(const payload of [{items:[{name:'db',password:'x'}]},{items:[{name:'oauth',accessToken:'x'}]},{items:[{name:'api',credentials:{value:'x'}}]}]){const response=await app.inject({method:'PUT',url:'/v1/control/pages/secrets',headers,payload});assert.equal(response.statusCode,400);assert.equal(response.json().error.code,'PLAINTEXT_SECRET_FORBIDDEN')}});
  await t.test('secrets page stores and returns metadata only',async()=>{const response=await app.inject({method:'PUT',url:'/v1/control/pages/secrets',headers,payload:{items:[{name:'database/master',provider:'aws-secrets-manager',configured:true,health:'HEALTHY',rotationStatus:'SCHEDULED',lastRotation:'2026-09-20T00:00:00Z'}]}});assert.equal(response.statusCode,200);const read=await app.inject({method:'GET',url:'/v1/control/secrets',headers});assert.equal(read.statusCode,200);assert.equal(read.json().data.items[0].name,'database/master');assert.equal(JSON.stringify(read.json()).includes('password'),false)});
  await t.test('privileged control-plane access requires MFA even for dev tokens',async()=>{const noMfa='dev.'+Buffer.from(JSON.stringify({userId:'operator-2',tenantId:'platform',roles:['platform-admin'],permissions:['platform:write'],mfa:false})).toString('base64url');const response=await app.inject({method:'GET',url:'/v1/control/overview',headers:{authorization:`Bearer ${noMfa}`}});assert.equal(response.statusCode,403);assert.equal(response.json().error.code,'MFA_REQUIRED_FOR_PRIVILEGED_ROLE')});
  await t.test('privileged read-only operator cannot mutate control-plane state',async()=>{const readOnly='dev.'+Buffer.from(JSON.stringify({userId:'operator-3',tenantId:'platform',roles:['platform-admin'],permissions:['platform:read'],mfa:true})).toString('base64url');const readHeaders={authorization:`Bearer ${readOnly}`};assert.equal((await app.inject({method:'GET',url:'/v1/control/overview',headers:readHeaders})).statusCode,200);const response=await app.inject({method:'POST',url:'/v1/control/changes',headers:readHeaders,payload:{environment:'development',operation:'disable-capability',capability:'cache',desired:{enabled:false,fallback:'memory'}}});assert.equal(response.statusCode,403);assert.equal(response.json().error.code,'PLATFORM_WRITE_PERMISSION_REQUIRED')});

});
