import test from 'node:test';
import assert from 'node:assert/strict';
import { InProcessOutboxEventBus, MemoryCacheAdapter, MemoryObjectStorage } from '../packages/platform-sdk/src/fallbacks.js';
import { TenantScopedAI, TenantScopedCache, TenantScopedEventBus, TenantScopedJobQueue, TenantScopedObjectStorage, TenantScopedSearch, TenantScopedSecretProvider } from '../packages/security/src/tenant-scoped-ports.js';
import { assertTenantWebhook, tenantWebhookEnvelope } from '../packages/security/src/tenant-context.js';
import type { AIModelPort, JobQueuePort, SearchPort, SecretProvider } from '../packages/capability-contracts/src/index.js';

const healthy=async()=>({status:'HEALTHY' as const,checkedAt:new Date().toISOString()});
test('cache namespaces cannot collide across tenants',async()=>{const base=new MemoryCacheAdapter();const a=new TenantScopedCache(base,{tenantId:'a',workspaceId:'w'});const b=new TenantScopedCache(base,{tenantId:'b',workspaceId:'w'});await a.set('same','A');await b.set('same','B');assert.equal(await a.get('same'),'A');assert.equal(await b.get('same'),'B')});
test('search wrapper injects tenant scope and rejects cross-tenant requests',async()=>{let seen='';const delegate:SearchPort={search:async q=>{seen=q.tenantId;return{hits:[],tookMs:0}},health:healthy};const scoped=new TenantScopedSearch(delegate,{tenantId:'a',workspaceId:'w'});await scoped.search({text:'x'});assert.equal(seen,'a');await assert.rejects(()=>scoped.search({text:'x',tenantId:'b'}),/CROSS_TENANT_SEARCH_DENIED/)});
test('object storage keys are transparently tenant/workspace scoped',async()=>{const base=new MemoryObjectStorage();const a=new TenantScopedObjectStorage(base,{tenantId:'a',workspaceId:'w'});const b=new TenantScopedObjectStorage(base,{tenantId:'b',workspaceId:'w'});await a.put('same.txt',new TextEncoder().encode('A'));await b.put('same.txt',new TextEncoder().encode('B'));assert.equal(new TextDecoder().decode(await a.get('same.txt')),'A');assert.equal(new TextDecoder().decode(await b.get('same.txt')),'B');await assert.rejects(()=>a.put('../escape',new Uint8Array([1])),/INVALID_TENANT_STORAGE_KEY/)});
test('job queue wrapper injects tenant envelope and tenant-scopes idempotency keys',async()=>{let seen:any;const delegate:JobQueuePort={enqueue:async(_queue,payload,options)=>{seen={payload,options};return'job-1'},health:healthy};const scoped=new TenantScopedJobQueue(delegate,{tenantId:'a',workspaceId:'w'});await scoped.enqueue('reports',{reportId:'r1'},{idempotencyKey:'same'});assert.equal(seen.payload.tenantId,'a');assert.equal(seen.payload.workspaceId,'w');assert.match(seen.options.idempotencyKey,/tenant:a:workspace:w:job-idempotency:same/)});
test('event and AI wrappers reject cross-tenant context',async()=>{const bus=new TenantScopedEventBus(new InProcessOutboxEventBus(),{tenantId:'a',workspaceId:'w'});await assert.rejects(()=>bus.publish({eventId:'e',eventType:'x',eventVersion:1,timestamp:new Date().toISOString(),tenantId:'b',workspaceId:'w',correlationId:'c',source:'test',data:{}}),/CROSS_TENANT_EVENT_DENIED/);let seenTenant='';const aiDelegate:AIModelPort={generate:async req=>{seenTenant=req.tenantId;return{output:'ok',model:'m',inputTokens:1,outputTokens:1,provider:'test'}},health:healthy};const ai=new TenantScopedAI(aiDelegate,{tenantId:'a',workspaceId:'w'});await ai.generate({tenantId:'a',workspaceId:'w',input:'hi',correlationId:'c'});assert.equal(seenTenant,'a');await assert.rejects(()=>ai.generate({tenantId:'b',workspaceId:'w',input:'hi',correlationId:'c'}),/CROSS_TENANT_AI_DENIED/)});
test('integration credential names and webhook envelopes are tenant/workspace scoped',async()=>{let requested='';const delegate:SecretProvider={get:async name=>{requested=name;return'ok'},health:healthy};const scoped=new TenantScopedSecretProvider(delegate,{tenantId:'a',workspaceId:'w'});assert.equal(await scoped.get('whatsapp/access-token'),'ok');assert.equal(requested,'tenants/a/workspaces/w/integrations/whatsapp/access-token');await assert.rejects(()=>scoped.get('../escape'),/INVALID_TENANT_CREDENTIAL_NAME/);const envelope=tenantWebhookEnvelope({tenantId:'a',workspaceId:'w'},'whatsapp',{messageId:'m'});assert.doesNotThrow(()=>assertTenantWebhook({tenantId:'a',workspaceId:'w'},envelope));assert.throws(()=>assertTenantWebhook({tenantId:'b',workspaceId:'w'},envelope),/CROSS_TENANT_WEBHOOK_DENIED/)});
