name: aws-platform

services:
  postgres:
    image: postgres:16.4-alpine3.20
    profiles: ["minimal","standard","full"]
    environment:
      POSTGRES_DB: platform
      POSTGRES_USER: platform
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U platform -d platform"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ../..
      dockerfile: infrastructure/docker/api.Dockerfile
    profiles: ["minimal","standard","full"]
    depends_on:
      postgres:
        condition: service_healthy
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    stop_grace_period: 30s

  web:
    build:
      context: ../..
      dockerfile: infrastructure/docker/web.Dockerfile
    profiles: ["minimal","standard","full"]
    depends_on:
      - api
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  redis:
    image: redis:7.4.1-alpine3.20
    profiles: ["standard","full"]

  localstack:
    image: localstack/localstack:3.7.2
    profiles: ["standard","full"]
    environment:
      SERVICES: sqs

  worker:
    build:
      context: ../..
      dockerfile: infrastructure/docker/api.Dockerfile
    profiles: ["standard","full"]
    environment:
      ROLE: worker
    depends_on:
      - api
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  kafka:
    image: bitnami/kafka:3.8.0
    profiles: ["full"]
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

volumes:
  postgres_data:

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
