export type WorkflowKind='redis-off'|'kafka-off'|'opensearch-off'|'eks-to-ecs'|'ai-off'|'ai-provider-switch';
export interface WorkflowContext{environment:'development'|'testing'|'staging'|'production';actorRoles:string[];fallbacksHealthy:boolean;databaseCapacitySafe?:boolean;alternateEventBusHealthy?:boolean;kafkaOnlyConsumers?:number;consumerLag?:number;dlqHealthy?:boolean;schemaCompatible?:boolean;postgresSearchIndexesHealthy?:boolean;shadowSearchCorrect?:boolean;shadowSearchLatencyAcceptable?:boolean;targetComputeHealthy?:boolean;aiFallbackHealthy?:boolean}
export interface WorkflowStep{id:string;action:string;gate?:string;rollbackOnFailure?:boolean}
export interface SwitchWorkflow{kind:WorkflowKind;risk:'BLUE'|'AMBER'|'RED';steps:WorkflowStep[];destructive:false}
export class WorkflowPreconditionError extends Error{constructor(public readonly code:string,message:string){super(`${code}: ${message}`);this.name='WorkflowPreconditionError'}}
function privileged(ctx:WorkflowContext){if(!ctx.actorRoles.some(r=>['platform-admin','sre','security-admin'].includes(r)))throw new WorkflowPreconditionError('RBAC_DENIED','Privileged platform role required.')}
export function planRedisOff(ctx:WorkflowContext):SwitchWorkflow{privileged(ctx);if(!ctx.fallbacksHealthy)throw new WorkflowPreconditionError('FALLBACK_UNHEALTHY','Redis fallbacks must be healthy.');if(ctx.databaseCapacitySafe===false)throw new WorkflowPreconditionError('DATABASE_CAPACITY_UNSAFE','Database capacity unsafe.');return{kind:'redis-off',risk:'BLUE',destructive:false,steps:[
{id:'1',action:'validate RBAC and environment policy'},{id:'2',action:'resolve dependency graph'},{id:'3',action:'verify memory/no-cache, PostgreSQL lock/idempotency, queue and pub/sub fallbacks'},{id:'4',action:'estimate increased PostgreSQL load',gate:'database capacity safe'},{id:'5',action:'create auditable change request and impact report'},{id:'6',action:'obtain approval when production',gate:ctx.environment==='production'?'approval required':'not required'},{id:'7',action:'roll out provider switch gradually',rollbackOnFailure:true},{id:'8',action:'verify cache bypass, locks, sessions, idempotency and queue behavior',rollbackOnFailure:true},{id:'9',action:'observe latency/errors/database metrics',rollbackOnFailure:true},{id:'10',action:'mark Redis disabled only after health passes'},{id:'11',action:'keep Redis infrastructure intact'},{id:'12',action:'rollback on SLO or health failure',rollbackOnFailure:true}]}}
export function planKafkaOff(ctx:WorkflowContext):SwitchWorkflow{privileged(ctx);if(!ctx.alternateEventBusHealthy)throw new WorkflowPreconditionError('EVENTBUS_FALLBACK_UNHEALTHY','Healthy alternate EventBusPort required.');if((ctx.kafkaOnlyConsumers??0)>0)throw new WorkflowPreconditionError('KAFKA_ONLY_CONSUMERS','Kafka-only consumers remain.');if((ctx.consumerLag??0)>0)throw new WorkflowPreconditionError('CONSUMER_LAG_PRESENT','Drain consumer lag.');if(ctx.dlqHealthy===false||ctx.schemaCompatible===false)throw new WorkflowPreconditionError('EVENTING_HEALTH_FAILED','DLQ/schema checks failed.');return{kind:'kafka-off',risk:'BLUE',destructive:false,steps:[{id:'1',action:'verify transactional outbox'},{id:'2',action:'verify alternate event bus, lag, DLQ, schemas and consumers'},{id:'3',action:'dual-route only if migration needs it; consumers idempotent'},{id:'4',action:'cut EventBusPort to outbox -> SNS/SQS/local dispatcher',rollbackOnFailure:true},{id:'5',action:'verify no event loss via outbox/inbox',rollbackOnFailure:true},{id:'6',action:'mark Kafka disabled while MSK infrastructure remains intact'}]}}
export function planOpenSearchOff(ctx:WorkflowContext):SwitchWorkflow{privileged(ctx);if(!ctx.postgresSearchIndexesHealthy)throw new WorkflowPreconditionError('POSTGRES_SEARCH_UNHEALTHY','PostgreSQL search indexes unhealthy.');if(!ctx.shadowSearchCorrect||!ctx.shadowSearchLatencyAcceptable)throw new WorkflowPreconditionError('SHADOW_SEARCH_FAILED','Shadow search failed.');return{kind:'opensearch-off',risk:'BLUE',destructive:false,steps:[{id:'1',action:'verify PostgreSQL full-text indexes'},{id:'2',action:'run shadow queries and compare correctness/latency'},{id:'3',action:'switch SearchPort reads to PostgreSQL',rollbackOnFailure:true},{id:'4',action:'observe search errors and latency',rollbackOnFailure:true},{id:'5',action:'disable OpenSearch application usage; destroy remains separate'}]}}
export function planEksToEcs(ctx:WorkflowContext):SwitchWorkflow{privileged(ctx);if(ctx.targetComputeHealthy===false)throw new WorkflowPreconditionError('TARGET_COMPUTE_UNHEALTHY','ECS target unhealthy.');return{kind:'eks-to-ecs',risk:'RED',destructive:false,steps:[{id:'1',action:'provision parallel ECS target'},{id:'2',action:'deploy exact same immutable images'},{id:'3',action:'validate target health',gate:'target healthy'},{id:'4',action:'shift traffic 5%',rollbackOnFailure:true},{id:'5',action:'shift traffic 25%',rollbackOnFailure:true},{id:'6',action:'shift traffic 50%',rollbackOnFailure:true},{id:'7',action:'shift traffic 100%',rollbackOnFailure:true},{id:'8',action:'drain EKS source'},{id:'9',action:'disable EKS placement; removal is separate approved IaC action'}]}}
export function planAiChange(ctx:WorkflowContext,disable:boolean):SwitchWorkflow{privileged(ctx);if(!disable&&ctx.aiFallbackHealthy===false)throw new WorkflowPreconditionError('AI_TARGET_UNHEALTHY','AI target unhealthy.');return{kind:disable?'ai-off':'ai-provider-switch',risk:'BLUE',destructive:false,steps:[{id:'1',action:'route through AIModelPort / AI Gateway'},{id:'2',action:'disable AI UI actions cleanly'},{id:'3',action:'return CAPABILITY_UNAVAILABLE instead of generic 500s'},{id:'4',action:'stop/suspend AI workers and scale GPU to zero'},{id:'5',action:'verify unrelated modules remain healthy',rollbackOnFailure:true},{id:'6',action:disable?'mark AI disabled':'cut AIModelPort to target provider and verify telemetry',rollbackOnFailure:true}]}}
export function planSwitch(kind:WorkflowKind,ctx:WorkflowContext):SwitchWorkflow{if(kind==='redis-off')return planRedisOff(ctx);if(kind==='kafka-off')return planKafkaOff(ctx);if(kind==='opensearch-off')return planOpenSearchOff(ctx);if(kind==='eks-to-ecs')return planEksToEcs(ctx);return planAiChange(ctx,kind==='ai-off')}
